// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcp_33bAzeMT5M33izJGXe3_HsfrMEdj0',
    appId: '1:338644235525:web:f68b8312d71e817d8b736c',
    messagingSenderId: '338644235525',
    projectId: 'prueba-maps-23af7',
    authDomain: 'prueba-maps-23af7.firebaseapp.com',
    storageBucket: 'prueba-maps-23af7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHPyOn_SP--N6frijrwQXm3AU5iW23JHY',
    appId: '1:338644235525:android:7452a64b7761e2138b736c',
    messagingSenderId: '338644235525',
    projectId: 'prueba-maps-23af7',
    storageBucket: 'prueba-maps-23af7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_qrE6HQMu95agZW2bxxHyOS6WOaot8uk',
    appId: '1:338644235525:ios:c50ed6fe0965cabe8b736c',
    messagingSenderId: '338644235525',
    projectId: 'prueba-maps-23af7',
    storageBucket: 'prueba-maps-23af7.firebasestorage.app',
    iosBundleId: 'com.example.pruebaMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_qrE6HQMu95agZW2bxxHyOS6WOaot8uk',
    appId: '1:338644235525:ios:c50ed6fe0965cabe8b736c',
    messagingSenderId: '338644235525',
    projectId: 'prueba-maps-23af7',
    storageBucket: 'prueba-maps-23af7.firebasestorage.app',
    iosBundleId: 'com.example.pruebaMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcp_33bAzeMT5M33izJGXe3_HsfrMEdj0',
    appId: '1:338644235525:web:84c7d0b10ded5e348b736c',
    messagingSenderId: '338644235525',
    projectId: 'prueba-maps-23af7',
    authDomain: 'prueba-maps-23af7.firebaseapp.com',
    storageBucket: 'prueba-maps-23af7.firebasestorage.app',
  );
}
